### ISSUE TITLE
[Feature request]关于git使用的提问

### ISSUE THREAD

**Issue by HereIsZephyrus** [Keruone/learngit#1]
学长学长git 怎么用啊(眨眼睛)

**Comment by Keruone** [comment]
学长学长教教我呗，我也不会用desu（眨眼睛）

**Comment by Keruone** [comment]
> 学长学长git 怎么用啊(眨眼睛)
学长学长教教我呗，我也不会用desu（眨眼睛）

**Comment by HereIsZephyrus** [comment]
It seems that you attempted to include a quoted comment in your response, but it isn't displaying correctly. To ensure proper rendering of your markdown, I recommend clicking on the "Preview" button to review how it appears. It's important to note that different renderers may have varying behaviors. You can consult the manual to understand how the GitHub markdown renderer functions. In most renderers, a blank line is necessary to separate the quote block from the normal block.
This is the correct way:
```
> 学长学长git 怎么用啊(眨眼睛)

学长学长教教我呗，我也不会用desu（眨眼睛）
```
And here is the result:
> 学长学长git 怎么用啊(眨眼睛)

学长学长教教我呗，我也不会用desu（眨眼睛）
